### ISSUE TITLE
[Config] Redis 사용을 위한 설정

### ISSUE THREAD

**Issue by flimberkim** [KDT3-final-project-team2/backend#12]
## 🔨개발 할 기능
- Redis 설정

## 🧩 세부 기능
해당 기능에 대한 세부 계획 작성
- [x] build.gradle에 implementation 추가
- [x] Config 및 Repository 생성

**Comment by HongGuma** [comment]
fix 보다는 conf 로 변경하는게 어떨까요?

**Comment by flimberkim** [comment]
> fix 보다는 conf 로 변경하는게 어떨까요?

👍

**Comment by 724thomas** [comment]
fix 보다는 conf 로 변경하는게 어떨까요?

**Comment by flimberkim** [comment]
> fix 보다는 conf 로 변경하는게 어떨까요?

이미 바꿨습니다^^ (부들부들)
