### ISSUE TITLE
[Feat] 기업 약관 CRUD 

### ISSUE THREAD

**Issue by HongGuma** [KDT3-final-project-team2/backend#55]
## 🔨개발 할 기능
기업 약관 CRUD

## 🧩 세부 기능
- [x] 기업 약관 리스트 출력 DTO 생성
- [x] 기업 약관 단건 출력 DTO 생성
- [x] 기업 약관 출력 기능 구현
- [x] 기업 약관 수정용 DTO 생성
- [x] 기업 약관 수정 기능 구현

## 📖 참고 사항
delete보다는 상태값을 폐기로 변경

**Comment by smallsnail-study** [comment]
기능구현 완료
