### ISSUE TITLE
[Config] 프로젝트 초기세팅

### ISSUE THREAD

**Issue by 724thomas** [KDT3-final-project-team2/backend#8]
## 🔨개발 할 기능
CICD 초기세팅 수정, application.properties에 database 초기세팅

## 🧩 세부 기능
해당 기능에 대한 세부 계획 작성 (ex. -[ ] 로그인 시 아이디 비번 입력 받기)
- [ ] main.yml 파일의 master -> dev 로 변경
- [ ] application.properties 초기 파일 작성

**Comment by HongGuma** [comment]
config 로 변경 하셨네요 ^^ 굿~~~

**Comment by flimberkim** [comment]
원준님 이번 이슈는 fix보다는 config가 낫지 않을까요^^????
